/**
 * jQuery.share - social media sharing plugin
 * ---
 * @author Carol Skelly (http://in1.com)
 * @version 1.0
 * @license MIT license (http://opensource.org/licenses/mit-license.php)
 * ---
 */

!function(a,b){var d=b.document;a.fn.share=function(c){var e={init:function(c){this.share.settings=a.extend({},this.share.defaults,c);var g=(this.share.settings,this.share.settings.networks),h=this.share.settings.theme,i=this.share.settings.orientation,j=this.share.settings.affix,k=this.share.settings.margin,l=this.share.settings.title||a(d).attr("title"),m=this.share.settings.urlToShare||a(location).attr("href"),n="";return a.each(a(d).find('meta[name="description"]'),function(b,c){n=a(c).attr("content")}),this.each(function(){var q,c=a(this),d=c.attr("id"),e=encodeURIComponent(m),o=encodeURIComponent(l),p=n.substring(0,250);for(var r in g)r=g[r],q=f.networkDefs[r].url,q=q.replace("|u|",e).replace("|t|",o).replace("|d|",p).replace("|140|",o.substring(0,130)),a("<a href='"+q+"' title='Share this page on "+r+"' class='pop share-"+h+" share-"+h+"-"+r+"'></a>").appendTo(c);a("#"+d+".share-"+h).css("margin",k),"horizontal"!=i?a("#"+d+" a.share-"+h).css("display","block"):a("#"+d+" a.share-"+h).css("display","inline-block"),"undefined"!=typeof j&&(c.addClass("share-affix"),-1!=j.indexOf("right")?(c.css("left","auto"),c.css("right","0px"),-1!=j.indexOf("center")&&c.css("top","40%")):-1!=j.indexOf("left center")&&c.css("top","40%"),-1!=j.indexOf("bottom")&&(c.css("bottom","0px"),c.css("top","auto"),-1!=j.indexOf("center")&&c.css("left","40%"))),a(".pop").click(function(){return b.open(a(this).attr("href"),"t","toolbar=0,resizable=1,status=0,width=640,height=528"),!1})})}},f={networkDefs:{facebook:{url:"http://www.facebook.com/share.php?u=|u|"},twitter:{url:"https://twitter.com/share?url=|u|&text=|140|"},linkedin:{url:"http://www.linkedin.com/shareArticle?mini=true&url=|u|&title=|t|&summary=|d|&source=in1.com"},in1:{url:"http://www.in1.com/cast?u=|u|",w:"490",h:"529"},tumblr:{url:"http://www.tumblr.com/share?v=3&u=|u|"},digg:{url:"http://digg.com/submit?url=|u|&title=|t|"},googleplus:{url:"https://plusone.google.com/_/+1/confirm?hl=en&url=|u|"},reddit:{url:"http://reddit.com/submit?url=|u|"},pinterest:{url:"http://pinterest.com/pin/create/button/?url=|u|&media=&description=|d|"},posterous:{url:"http://posterous.com/share?linkto=|u|&title=|t|"},stumbleupon:{url:"http://www.stumbleupon.com/submit?url=|u|&title=|t|"},email:{url:"mailto:?subject=|t|"}}};return e[c]?e[c].apply(this,Array.prototype.slice.call(arguments,1)):"object"!=typeof c&&c?(a.error('Method "'+c+'" does not exist in social plugin'),void 0):e.init.apply(this,arguments)},a.fn.share.defaults={networks:["facebook","twitter","linkedin"],theme:"icon",autoShow:!0,margin:"3px",orientation:"horizontal",useIn1:!1},a.fn.share.settings={}}(jQuery,window);